#!/usr/bin/env python3
"""Build searchable CSV and Markdown indexes for official relic sources."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path

from official_reference_common import localization_id, markdown_cell, normalize_code, plain_chinese, read_localization, relative_source, unique_matches, write_csv


HEADERS = ["ClassName", "LocalizationId", "ChineseTitle", "ChineseDescription", "ChinesePlainText", "ChineseFlavor", "Pools", "Rarity", "DynamicVars", "Hooks", "ImplementationCalls", "SourcePath"]


def main() -> int:
    workspace = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, default=workspace / "OfficialReference" / "SlayTheSpire2")
    parser.add_argument("--output-dir", type=Path, default=workspace / "OfficialReference" / "generated")
    parser.add_argument("--localization-path", type=Path, default=workspace / "OfficialReference" / "localization" / "zhs" / "relics.json")
    args = parser.parse_args()
    source_root, output_dir, localization_path = args.source_root.resolve(), args.output_dir.resolve(), args.localization_path.resolve()
    relics_dir, pools_dir = source_root / "MegaCrit.Sts2.Core.Models.Relics", source_root / "MegaCrit.Sts2.Core.Models.RelicPools"
    if not relics_dir.is_dir():
        raise FileNotFoundError(f"Official relic source directory not found: {relics_dir}. Run export_official_source.py first.")
    if not pools_dir.is_dir():
        raise FileNotFoundError(f"Official relic pool source directory not found: {pools_dir}")
    localization = read_localization(localization_path)
    pool_by_relic: dict[str, list[str]] = defaultdict(list)
    for path in pools_dir.glob("*RelicPool.cs"):
        pool = path.stem.removesuffix("RelicPool")
        for relic in re.findall(r"ModelDb\.Relic<([A-Za-z_][A-Za-z0-9_]*)>", path.read_text(encoding="utf-8-sig")):
            if pool not in pool_by_relic[relic]:
                pool_by_relic[relic].append(pool)
    rows: list[dict[str, str]] = []
    for path in relics_dir.rglob("*.cs"):
        text = path.read_text(encoding="utf-8-sig")
        match = re.search(r"public\s+(?:sealed\s+)?class\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*RelicModel\b", text)
        if not match:
            continue
        class_name, loc_id = match.group(1), localization_id(match.group(1))
        rarity_match = re.search(r"RelicRarity\s+Rarity\s*=>\s*RelicRarity\.([A-Za-z_][A-Za-z0-9_]*)", text)
        dynamic_vars: list[str] = []
        for var in re.finditer(r"new\s+([A-Za-z_][A-Za-z0-9_]*Var)\s*\(([^\r\n)]*)\)", text):
            value = f"{var.group(1)}({normalize_code(var.group(2))})"
            if value not in dynamic_vars:
                dynamic_vars.append(value)
        description = localization.get(f"{loc_id}.description", "")
        rows.append({
            "ClassName": class_name, "LocalizationId": loc_id, "ChineseTitle": localization.get(f"{loc_id}.title", ""),
            "ChineseDescription": description, "ChinesePlainText": plain_chinese(description), "ChineseFlavor": localization.get(f"{loc_id}.flavor", ""),
            "Pools": "; ".join(pool_by_relic.get(class_name, [])) or "Unassigned", "Rarity": rarity_match.group(1) if rarity_match else "",
            "DynamicVars": "; ".join(dynamic_vars),
            "Hooks": "; ".join(unique_matches(text, r"public\s+override\s+(?:async\s+)?[^\r\n\{=]+?\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(")),
            "ImplementationCalls": "; ".join(unique_matches(text, r"([A-Za-z_][A-Za-z0-9_]*(?:Cmd|Command)\.[A-Za-z_][A-Za-z0-9_]*)")),
            "SourcePath": relative_source(path, workspace),
        })
    rows.sort(key=lambda row: (row["Pools"], row["ChineseTitle"], row["ClassName"]))
    if not rows:
        raise RuntimeError(f"No concrete RelicModel implementations were indexed from {relics_dir}")
    write_csv(output_dir / "RelicIndex.csv", HEADERS, rows)
    md = ["# Official Relic Reference Index", "", "Generated from the locally decompiled `sts2.dll` and official Simplified Chinese localization. Regenerate with `scripts/build_official_relic_index.py`; do not edit this file manually.", "", "| 中文名 | Class | Pools | Rarity | 中文效果 | Dynamic vars | Hooks | Implementation calls | Source |", "|---|---|---|---|---|---|---|---|---|"]
    for row in rows:
        source = row["SourcePath"].removeprefix("OfficialReference/")
        cells = [row[key] for key in ("ChineseTitle", "ClassName", "Pools", "Rarity", "ChineseDescription", "DynamicVars", "Hooks", "ImplementationCalls")]
        md.append("| " + " | ".join(markdown_cell(value) for value in cells) + f" | [source](../{source}) |")
    (output_dir / "RelicIndex.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    pool_counts = {pool: sum(row["Pools"] == pool for row in rows) for pool in sorted({row["Pools"] for row in rows})}
    summary = [f"Generated: {datetime.now().isoformat(timespec='seconds')}", f"Source: {source_root}", f"Relics: {len(rows)}", f"Localized titles: {sum(bool(row['ChineseTitle']) for row in rows)}", f"Localized descriptions: {sum(bool(row['ChineseDescription']) for row in rows)}", f"Missing localized titles: {sum(not row['ChineseTitle'] for row in rows)}", f"Localization: {localization_path}", "Pools:"] + [f"  {pool}: {count}" for pool, count in pool_counts.items()]
    (output_dir / "RelicIndexSummary.txt").write_text("\n".join(summary) + "\n", encoding="utf-8")
    print(f"RELIC_INDEX_OK relics={len(rows)} csv={output_dir / 'RelicIndex.csv'} markdown={output_dir / 'RelicIndex.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
